### ISSUE TITLE
DomainOntology's getAllVariables doesn't work properly

### ISSUE THREAD

**Issue by jianlins** [Blulab-Utah/domainOntology#10]
I request a pull for new testAPI. The output shows that getAllVariables gets nothing.

**Comment by mecst76** [comment]
I've attached the code that I used and the results. I cannot replicate your problem. Can you please send me the .owl file that you are trying to process and/or the code that you have written so that I can better assist you?
[chfTest.txt](https://github.com/Blulab-Utah/domainOntology/files/218174/chfTest.txt)
[csi_chf_output.txt](https://github.com/Blulab-Utah/domainOntology/files/218175/csi_chf_output.txt)

**Comment by jianlins** [comment]
It appears to be my fault. I used the wrong owl file again (in the resources folder). I've update the owl file. The new testAPI should be useful and easier to test most of the methods.
